Program(
  Statements(
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "Grade"
        ),
        TOKEN_OPERATOR: "=",
        Expression(
          Term(
            Factor(
              Power(
                TOKEN_NUMBER: "1.0"
              )
            )
          )
        ),
        TOKEN_SEMI
      )
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "score"
        ),
        TOKEN_OPERATOR: "+=",
        Expression(
          Term(
            Factor(
              Power(
                TOKEN_NUMBER: "1"
              )
            )
          )
        ),
        TOKEN_SEMI
      )
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "result"
        ),
        TOKEN_OPERATOR: "=",
        Expression(
          Term(
            Factor(
              Power(
                TOKEN_LPAREN,
                Expression(
                  Term(
                    Factor(
                      Power(
                        TOKEN_ID: "x"
                      )
                    )
                  ),
                  TOKEN_OPERATOR: "+",
                  Term(
                    Factor(
                      Power(
                        TOKEN_NUMBER: "2"
                      )
                    )
                  )
                ),
                TOKEN_RPAREN
              )
            ),
            TOKEN_OPERATOR: "*",
            Factor(
              Power(
                TOKEN_ID: "z"
              )
            ),
            TOKEN_OPERATOR: "/",
            Factor(
              Power(
                TOKEN_LPAREN,
                Expression(
                  Term(
                    Factor(
                      Power(
                        TOKEN_ID: "y"
                      ),
                      TOKEN_OPERATOR: "**",
                      Power(
                        TOKEN_NUMBER: "2"
                      )
                    )
                  )
                ),
                TOKEN_RPAREN
              )
            )
          ),
          TOKEN_OPERATOR: "-",
          Term(
            Factor(
              Power(
                TOKEN_NUMBER: "5"
              )
            )
          )
        ),
        TOKEN_SEMI
      )
    ),
    Statement(
      Conditional(
        TOKEN_IF,
        TOKEN_LPAREN,
        Bool Expression(
          Bool Term(
            Bool Factor(
              TOKEN_ID: "age"
            ),
            TOKEN_OPERATOR: "and",
            Bool Factor(
              TOKEN_ID: "height"
            )
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Assignment(
                Identifier(
                  TOKEN_ID: "Grade"
                ),
                TOKEN_OPERATOR: "=",
                Expression(
                  Term(
                    Factor(
                      Power(
                        TOKEN_NUMBER: "1.0"
                      )
                    )
                  )
                ),
                TOKEN_SEMI
              )
            ),
            Statement(
              Assignment(
                Identifier(
                  TOKEN_ID: "score"
                ),
                TOKEN_OPERATOR: "+=",
                Expression(
                  Term(
                    Factor(
                      Power(
                        TOKEN_NUMBER: "1"
                      )
                    )
                  )
                ),
                TOKEN_SEMI
              )
            ),
            Statement(
              Output(
                TOKEN_ID: "print",
                TOKEN_LPAREN,
                Print Expression(
                  Expression(
                    Term(
                      Factor(
                        Power(
                          TOKEN_ID: "HEY"
                        )
                      )
                    ),
                    TOKEN_OPERATOR: "+",
                    Term(
                      Factor(
                        Power(
                          TOKEN_NUMBER: "5"
                        )
                      )
                    ),
                    TOKEN_OPERATOR: "+",
                    Term(
                      Factor(
                        Power(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            ),
            Statement(
              Output(
                TOKEN_ID: "print",
                TOKEN_LPAREN,
                Print Expression(
                  Expression(
                    Term(
                      Factor(
                        Power(
                          TOKEN_LPAREN,
                          Expression(
                            Term(
                              Factor(
                                Power(
                                  TOKEN_ID: "x"
                                )
                              ),
                              TOKEN_OPERATOR: "*",
                              Factor(
                                Power(
                                  TOKEN_ID: "y"
                                )
                              )
                            )
                          ),
                          TOKEN_RPAREN
                        )
                      ),
                      TOKEN_OPERATOR: "/",
                      Factor(
                        Power(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        ),
        Else(
          TOKEN_ELSE,
          Conditional(
            TOKEN_IF,
            TOKEN_LPAREN,
            Bool Expression(
              Bool Term(
                Bool Factor(
                  TOKEN_ID: "age"
                )
              ),
              TOKEN_OPERATOR: "or",
              Bool Term(
                Bool Factor(
                  TOKEN_ID: "height"
                )
              )
            ),
            TOKEN_RPAREN,
            Body(
              TOKEN_LBRACE,
              Statements(
                Statement(
                  Assignment(
                    Identifier(
                      TOKEN_ID: "grade"
                    ),
                    TOKEN_OPERATOR: "=",
                    Expression(
                      Term(
                        Factor(
                          Power(
                            TOKEN_NUMBER: "5"
                          )
                        )
                      ),
                      TOKEN_OPERATOR: "+",
                      Term(
                        Factor(
                          Power(
                            TOKEN_NUMBER: "5"
                          )
                        )
                      )
                    ),
                    TOKEN_SEMI
                  )
                )
              ),
              TOKEN_RBRACE
            ),
            Else(
              TOKEN_ELSE,
              Body(
                TOKEN_LBRACE,
                Statements(
                  Statement(
                    Output(
                      TOKEN_ID: "print",
                      TOKEN_LPAREN,
                      Print Expression(
                        Expression(
                          Term(
                            Factor(
                              Power(
                                TOKEN_ID: "age"
                              )
                            )
                          ),
                          TOKEN_OPERATOR: "+",
                          Term(
                            Factor(
                              Power(
                                TOKEN_ID: "height"
                              )
                            )
                          )
                        )
                      ),
                      TOKEN_RPAREN,
                      TOKEN_SEMI
                    )
                  )
                ),
                TOKEN_RBRACE
              )
            )
          )
        )
      )
    ),
    Statement(
      Return(
        TOKEN_RETURN,
        Expression(
          Term(
            Factor(
              Power(
                TOKEN_NUMBER: "5"
              )
            )
          ),
          TOKEN_OPERATOR: "+",
          Term(
            Factor(
              Power(
                TOKEN_NUMBER: "5"
              )
            )
          )
        ),
        TOKEN_SEMI
      )
    )
  )
)