Program(
  Statements(
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "Grade"
        ),
        TOKEN_OPERATOR: "=",
        Expression(
          Term(
            Power(
              Factor(
                Constant(
                  TOKEN_NUMBER: "1.0"
                )
              )
            )
          )
        )
      ),
      TOKEN_SEMI
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "score"
        ),
        TOKEN_OPERATOR: "+=",
        Expression(
          Term(
            Power(
              Factor(
                Constant(
                  TOKEN_NUMBER: "1"
                )
              )
            )
          )
        )
      ),
      TOKEN_SEMI
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "result"
        ),
        TOKEN_OPERATOR: "=",
        Expression(
          Term(
            Power(
              Factor(
                TOKEN_LPAREN,
                Expression(
                  Term(
                    Power(
                      Factor(
                        TOKEN_ID: "x"
                      )
                    )
                  ),
                  TOKEN_OPERATOR: "+",
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN
              )
            ),
            TOKEN_OPERATOR: "*",
            Power(
              Factor(
                TOKEN_ID: "z"
              )
            ),
            TOKEN_OPERATOR: "/",
            Power(
              Factor(
                TOKEN_LPAREN,
                Expression(
                  Term(
                    Power(
                      Factor(
                        TOKEN_ID: "y"
                      ),
                      TOKEN_OPERATOR: "**",
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN
              )
            )
          ),
          TOKEN_OPERATOR: "-",
          Term(
            Power(
              Factor(
                Constant(
                  TOKEN_NUMBER: "5"
                )
              )
            )
          )
        )
      ),
      TOKEN_SEMI
    ),
    Statement(
      Conditional(
        TOKEN_IF,
        TOKEN_LPAREN,
        Bool Expression(
          Bool Term(
            Bool Factor(
              TOKEN_ID: "age"
            ),
            TOKEN_OPERATOR: "and",
            Bool Factor(
              TOKEN_ID: "height"
            )
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Assignment(
                Identifier(
                  TOKEN_ID: "Grade"
                ),
                TOKEN_OPERATOR: "=",
                Expression(
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "1.0"
                        )
                      )
                    )
                  )
                )
              ),
              TOKEN_SEMI
            ),
            Statement(
              Assignment(
                Identifier(
                  TOKEN_ID: "score"
                ),
                TOKEN_OPERATOR: "+=",
                Expression(
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "1"
                        )
                      )
                    )
                  )
                )
              ),
              TOKEN_SEMI
            ),
            Statement(
              Output(
                TOKEN_ID: "print",
                TOKEN_LPAREN,
                Print Expression(
                  Expression(
                    Term(
                      Power(
                        Factor(
                          TOKEN_ID: "HEY"
                        )
                      )
                    ),
                    TOKEN_OPERATOR: "+",
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "5"
                          )
                        )
                      )
                    ),
                    TOKEN_OPERATOR: "+",
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "2"
                          )
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            ),
            Statement(
              Output(
                TOKEN_ID: "print",
                TOKEN_LPAREN,
                Print Expression(
                  Expression(
                    Term(
                      Power(
                        Factor(
                          TOKEN_LPAREN,
                          Expression(
                            Term(
                              Power(
                                Factor(
                                  TOKEN_ID: "x"
                                )
                              ),
                              TOKEN_OPERATOR: "*",
                              Power(
                                Factor(
                                  TOKEN_ID: "y"
                                )
                              )
                            )
                          ),
                          TOKEN_RPAREN
                        )
                      ),
                      TOKEN_OPERATOR: "/",
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "2"
                          )
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        ),
        Else(
          TOKEN_ELSE,
          Conditional(
            TOKEN_IF,
            TOKEN_LPAREN,
            Bool Expression(
              Bool Term(
                Bool Factor(
                  TOKEN_ID: "age"
                )
              ),
              TOKEN_OPERATOR: "or",
              Bool Term(
                Bool Factor(
                  Relational Expression(
                    Expression(
                      Term(
                        Power(
                          Factor(
                            TOKEN_ID: "height"
                          )
                        )
                      )
                    ),
                    TOKEN_OPERATOR: ">",
                    Expression(
                      Term(
                        Power(
                          Factor(
                            Constant(
                              TOKEN_NUMBER: "4"
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            ),
            TOKEN_RPAREN,
            Body(
              TOKEN_LBRACE,
              Statements(
                Statement(
                  Assignment(
                    Identifier(
                      TOKEN_ID: "grade"
                    ),
                    TOKEN_OPERATOR: "=",
                    Expression(
                      Term(
                        Power(
                          Factor(
                            Constant(
                              TOKEN_NUMBER: "5"
                            )
                          )
                        )
                      ),
                      TOKEN_OPERATOR: "+",
                      Term(
                        Power(
                          Factor(
                            Constant(
                              TOKEN_NUMBER: "5"
                            )
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_SEMI
                )
              ),
              TOKEN_RBRACE
            ),
            Else(
              TOKEN_ELSE,
              Body(
                TOKEN_LBRACE,
                Statements(
                  Statement(
                    Output(
                      TOKEN_ID: "print",
                      TOKEN_LPAREN,
                      Print Expression(
                        Expression(
                          Term(
                            Power(
                              Factor(
                                TOKEN_ID: "age"
                              )
                            )
                          ),
                          TOKEN_OPERATOR: "+",
                          Term(
                            Power(
                              Factor(
                                TOKEN_ID: "height"
                              )
                            )
                          )
                        ),
                        TOKEN_COMMA,
                        Print Expression(
                          Constant(
                            TOKEN_STRING: hello
                          ),
                          TOKEN_COMMA,
                          Print Expression(
                            Function Call(
                              Identifier(
                                TOKEN_ID: "add"
                              ),
                              TOKEN_LPAREN,
                              Expression(
                                Term(
                                  Power(
                                    Factor(
                                      Constant(
                                        TOKEN_NUMBER: "5"
                                      )
                                    )
                                  )
                                ),
                                TOKEN_OPERATOR: "+",
                                Term(
                                  Power(
                                    Factor(
                                      Constant(
                                        TOKEN_NUMBER: "5"
                                      )
                                    )
                                  )
                                )
                              ),
                              TOKEN_COMMA,
                              Expression(
                                Term(
                                  Power(
                                    Factor(
                                      Constant(
                                        TOKEN_NUMBER: "4"
                                      )
                                    )
                                  )
                                )
                              ),
                              TOKEN_COMMA,
                              Expression(
                                Term(
                                  Power(
                                    Factor(
                                      Constant(
                                        TOKEN_NUMBER: "2"
                                      )
                                    )
                                  )
                                )
                              ),
                              TOKEN_RPAREN
                            )
                          )
                        )
                      ),
                      TOKEN_RPAREN,
                      TOKEN_SEMI
                    )
                  )
                ),
                TOKEN_RBRACE
              )
            )
          )
        )
      )
    ),
    Statement(
      Function(
        TOKEN_FUNCTION,
        Identifier(
          TOKEN_ID: "sum"
        ),
        TOKEN_LPAREN,
        Parameter list(
          Datatype(
            TOKEN_DATATYPE: "float"
          ),
          Identifier(
            TOKEN_ID: "a"
          ),
          TOKEN_COMMA,
          TOKEN_DATATYPE: "char",
          Identifier(
            TOKEN_ID: "abby"
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Return(
                TOKEN_RETURN,
                Expression(
                  Term(
                    Power(
                      Factor(
                        TOKEN_LPAREN,
                        Expression(
                          Term(
                            Power(
                              Factor(
                                Constant(
                                  TOKEN_NUMBER: "5"
                                )
                              )
                            )
                          ),
                          TOKEN_OPERATOR: "+",
                          Term(
                            Power(
                              Factor(
                                Constant(
                                  TOKEN_NUMBER: "4"
                                )
                              )
                            )
                          )
                        ),
                        TOKEN_RPAREN
                      ),
                      TOKEN_OPERATOR: "**",
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        )
      )
    ),
    Statement(
      Iterative Statement(
        TOKEN_FOR,
        For Statement(
          TOKEN_LPAREN,
          Iterative Assignment statement(
            Identifier(
              TOKEN_ID: "i"
            ),
            TOKEN_OPERATOR: "=",
            Expression(
              Term(
                Power(
                  Factor(
                    Constant(
                      TOKEN_NUMBER: "0"
                    )
                  )
                )
              )
            )
          ),
          TOKEN_SEMI,
          Bool Expression(
            Bool Term(
              Bool Factor(
                Relational Expression(
                  Expression(
                    Term(
                      Power(
                        Factor(
                          TOKEN_ID: "i"
                        )
                      )
                    )
                  ),
                  TOKEN_OPERATOR: "<",
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "4"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          TOKEN_SEMI,
          Increment(
            Expression(
              Term(
                Power(
                  Factor(
                    TOKEN_ID: "i"
                  )
                )
              )
            ),
            TOKEN_OPERATOR: "++"
          ),
          TOKEN_RPAREN,
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Iterative Statement(
                  TOKEN_FOR,
                  For Statement(
                    TOKEN_LPAREN,
                    Iterative Assignment statement(
                      Datatype(
                        TOKEN_DATATYPE: "int"
                      ),
                      Identifier(
                        TOKEN_ID: "j"
                      ),
                      TOKEN_OPERATOR: "=",
                      Expression(
                        Term(
                          Power(
                            Factor(
                              Constant(
                                TOKEN_NUMBER: "1"
                              )
                            )
                          )
                        )
                      )
                    ),
                    TOKEN_SEMI,
                    Bool Expression(
                      Bool Term(
                        Bool Factor(
                          Relational Expression(
                            Expression(
                              Term(
                                Power(
                                  Factor(
                                    TOKEN_ID: "j"
                                  )
                                )
                              )
                            ),
                            TOKEN_OPERATOR: "<",
                            Expression(
                              Term(
                                Power(
                                  Factor(
                                    TOKEN_ID: "i"
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    ),
                    TOKEN_SEMI,
                    Increment(
                      Expression(
                        Term(
                          Power(
                            Factor(
                              TOKEN_ID: "j"
                            )
                          )
                        )
                      ),
                      TOKEN_OPERATOR: "++"
                    ),
                    TOKEN_RPAREN,
                    Body(
                      TOKEN_LBRACE,
                      TOKEN_RBRACE
                    )
                  )
                )
              )
            ),
            TOKEN_RBRACE
          )
        )
      )
    ),
    Statement(
      Iterative Statement(
        TOKEN_DO,
        Do While Statement(
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Output(
                  TOKEN_ID: "print",
                  TOKEN_LPAREN,
                  Print Expression(
                    Constant(
                      TOKEN_STRING: hi
                    )
                  ),
                  TOKEN_RPAREN,
                  TOKEN_SEMI
                )
              )
            ),
            TOKEN_RBRACE
          ),
          TOKEN_WHILE
        )
      )
    )
  )
)