Program(
  Statements(
    Statement(
      Output Statement(
        TOKEN_NOISE,
        TOKEN_LPAREN,
        Print Expression(
          Constant(
            TOKEN_STRING: Welcome to the program!
          )
        ),
        TOKEN_RPAREN,
        TOKEN_SEMI
      )
    ),
    Statement(
      Output Statement(
        TOKEN_NOISE,
        TOKEN_LPAREN,
        Print Expression(
          Constant(
            TOKEN_STRING: Result:
          ),
          TOKEN_COMMA,
          Print Expression(
            Expression(
              Term(
                Power(
                  Factor(
                    Identifier(
                      TOKEN_ID: "a"
                    )
                  )
                )
              ),
              TOKEN_OPERATOR: "+",
              Term(
                Power(
                  Factor(
                    Identifier(
                      TOKEN_ID: "b"
                    )
                  )
                )
              )
            ),
            TOKEN_COMMA,
            Print Expression(
              Expression(
                Term(
                  Power(
                    Factor(
                      Constant(
                        TOKEN_NUMBER: "30"
                      )
                    )
                  )
                )
              )
            )
          )
        ),
        TOKEN_RPAREN,
        TOKEN_SEMI
      )
    ),
    Statement(
      Output Statement(
        TOKEN_NOISE,
        TOKEN_LPAREN,
        Print Expression(
          Expression(
            Term(
              Power(
                Factor(
                  TOKEN_LPAREN,
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "x"
                          )
                        )
                      ),
                      TOKEN_OPERATOR: "*",
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "y"
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_RPAREN
                )
              ),
              TOKEN_OPERATOR: "/",
              Power(
                Factor(
                  Constant(
                    TOKEN_NUMBER: "2"
                  )
                )
              )
            )
          ),
          TOKEN_COMMA,
          Print Expression(
            Function Call(
              Identifier(
                TOKEN_ID: "max"
              ),
              TOKEN_LPAREN,
              Expression(
                Term(
                  Power(
                    Factor(
                      Constant(
                        TOKEN_NUMBER: "10"
                      )
                    )
                  )
                )
              ),
              TOKEN_COMMA,
              Expression(
                Term(
                  Power(
                    Factor(
                      Constant(
                        TOKEN_NUMBER: "20"
                      )
                    )
                  )
                )
              ),
              TOKEN_RPAREN
            )
          )
        ),
        TOKEN_RPAREN,
        TOKEN_SEMI
      )
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "Grade"
        ),
        TOKEN_OPERATOR: "=",
        Expression(
          Term(
            Power(
              Factor(
                Constant(
                  TOKEN_NUMBER: "1.0"
                )
              )
            )
          )
        )
      ),
      TOKEN_SEMI
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "score"
        ),
        TOKEN_OPERATOR: "+=",
        Expression(
          Term(
            Power(
              Factor(
                Constant(
                  TOKEN_NUMBER: "1"
                )
              )
            )
          )
        )
      ),
      TOKEN_SEMI
    ),
    Statement(
      Assignment(
        Identifier(
          TOKEN_ID: "result"
        ),
        TOKEN_OPERATOR: "=",
        Expression(
          Term(
            Power(
              Factor(
                TOKEN_LPAREN,
                Expression(
                  Term(
                    Power(
                      Factor(
                        Identifier(
                          TOKEN_ID: "x"
                        )
                      )
                    )
                  ),
                  TOKEN_OPERATOR: "+",
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN
              )
            ),
            TOKEN_OPERATOR: "*",
            Power(
              Factor(
                Identifier(
                  TOKEN_ID: "z"
                )
              )
            ),
            TOKEN_OPERATOR: "/",
            Power(
              Factor(
                TOKEN_LPAREN,
                Expression(
                  Term(
                    Power(
                      Factor(
                        Identifier(
                          TOKEN_ID: "y"
                        )
                      ),
                      TOKEN_OPERATOR: "**",
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2"
                        )
                      )
                    )
                  )
                ),
                TOKEN_RPAREN
              )
            )
          ),
          TOKEN_OPERATOR: "-",
          Term(
            Power(
              Factor(
                Constant(
                  TOKEN_NUMBER: "5"
                )
              )
            )
          )
        )
      ),
      TOKEN_SEMI
    ),
    Statement(
      Declaration statement(
        Function Statement(
          TOKEN_FUNCTION,
          Identifier(
            TOKEN_ID: "greetUser"
          ),
          TOKEN_LPAREN,
          Parameter List(),
          TOKEN_RPAREN,
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Output Statement(
                  TOKEN_NOISE,
                  TOKEN_LPAREN,
                  Print Expression(
                    Constant(
                      TOKEN_STRING: Hello user, welcome!
                    )
                  ),
                  TOKEN_RPAREN,
                  TOKEN_SEMI
                )
              )
            ),
            TOKEN_RBRACE
          )
        )
      )
    ),
    Statement(
      Conditional(
        TOKEN_IF,
        TOKEN_LPAREN,
        Bool Expression(
          Bool Term(
            Bool Factor(
              Relational Expression(
                Expression(
                  Term(
                    Power(
                      Factor(
                        Identifier(
                          TOKEN_ID: "height"
                        )
                      )
                    )
                  )
                ),
                TOKEN_OPERATOR: "==",
                Expression(
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2.1"
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Output Statement(
                TOKEN_NOISE,
                TOKEN_LPAREN,
                Print Expression(
                  Constant(
                    TOKEN_STRING: tall
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        )
      )
    ),
    Statement(
      Conditional(
        TOKEN_IF,
        TOKEN_LPAREN,
        Bool Expression(
          Bool Term(
            Bool Factor(
              Relational Expression(
                Expression(
                  Term(
                    Power(
                      Factor(
                        Identifier(
                          TOKEN_ID: "height"
                        )
                      )
                    )
                  )
                ),
                TOKEN_OPERATOR: ">=",
                Expression(
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2.1"
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Output Statement(
                TOKEN_NOISE,
                TOKEN_LPAREN,
                Print Expression(
                  Constant(
                    TOKEN_STRING: tall
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        ),
        Else(
          TOKEN_ELSE,
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Output Statement(
                  TOKEN_NOISE,
                  TOKEN_LPAREN,
                  Print Expression(
                    Constant(
                      TOKEN_STRING: short
                    )
                  ),
                  TOKEN_RPAREN,
                  TOKEN_SEMI
                )
              )
            ),
            TOKEN_RBRACE
          )
        )
      )
    ),
    Statement(
      Conditional(
        TOKEN_IF,
        TOKEN_LPAREN,
        Bool Expression(
          Bool Term(
            Bool Factor(
              Relational Expression(
                Expression(
                  Term(
                    Power(
                      Factor(
                        Identifier(
                          TOKEN_ID: "height"
                        )
                      )
                    )
                  )
                ),
                TOKEN_OPERATOR: ">=",
                Expression(
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2.1"
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Output Statement(
                TOKEN_NOISE,
                TOKEN_LPAREN,
                Print Expression(
                  Constant(
                    TOKEN_STRING: tall
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        ),
        Else(
          TOKEN_ELSE,
          Conditional(
            TOKEN_IF,
            TOKEN_LPAREN,
            Bool Expression(
              Bool Term(
                Bool Factor(
                  Relational Expression(
                    Expression(
                      Term(
                        Power(
                          Factor(
                            Identifier(
                              TOKEN_ID: "height"
                            )
                          )
                        )
                      )
                    ),
                    TOKEN_OPERATOR: "<=",
                    Expression(
                      Term(
                        Power(
                          Factor(
                            Constant(
                              TOKEN_NUMBER: "1.65"
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            ),
            TOKEN_RPAREN,
            Body(
              TOKEN_LBRACE,
              Statements(
                Statement(
                  Output Statement(
                    TOKEN_NOISE,
                    TOKEN_LPAREN,
                    Print Expression(
                      Constant(
                        TOKEN_STRING: short
                      )
                    ),
                    TOKEN_RPAREN,
                    TOKEN_SEMI
                  )
                )
              ),
              TOKEN_RBRACE
            ),
            Else(
              TOKEN_ELSE,
              Body(
                TOKEN_LBRACE,
                Statements(
                  Statement(
                    Output Statement(
                      TOKEN_NOISE,
                      TOKEN_LPAREN,
                      Print Expression(
                        Constant(
                          TOKEN_STRING: average
                        )
                      ),
                      TOKEN_RPAREN,
                      TOKEN_SEMI
                    )
                  )
                ),
                TOKEN_RBRACE
              )
            )
          )
        )
      )
    ),
    Statement(
      Iterative Statement(
        TOKEN_FOR,
        For Statement(
          TOKEN_LPAREN,
          Iterative Assignment statement(
            Data Type(
              TOKEN_DATATYPE: "int"
            ),
            Identifier(
              TOKEN_ID: "i"
            ),
            TOKEN_OPERATOR: "=",
            Expression(
              Term(
                Power(
                  Factor(
                    Constant(
                      TOKEN_NUMBER: "0"
                    )
                  )
                )
              )
            )
          ),
          TOKEN_SEMI,
          Bool Expression(
            Bool Term(
              Bool Factor(
                Relational Expression(
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "i"
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_OPERATOR: "<",
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "5"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          TOKEN_SEMI,
          Increment(
            Expression(
              Term(
                Power(
                  Factor(
                    Unary(
                      Identifier(
                        TOKEN_ID: "i"
                      ),
                      TOKEN_OPERATOR: "++"
                    )
                  )
                )
              )
            ),
            TOKEN_RPAREN
          ),
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Output Statement(
                  TOKEN_NOISE,
                  TOKEN_LPAREN,
                  Print Expression(
                    Expression(
                      Term(
                        Power(
                          Factor(
                            Identifier(
                              TOKEN_ID: "i"
                            )
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_RPAREN,
                  TOKEN_SEMI
                )
              )
            ),
            TOKEN_RBRACE
          )
        )
      )
    ),
    Statement(
      Iterative Statement(
        TOKEN_WHILE,
        While Statement(
          TOKEN_LPAREN,
          Bool Expression(
            Bool Term(
              Bool Factor(
                Relational Expression(
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "x"
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_OPERATOR: ">",
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "0"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          TOKEN_RPAREN,
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Output Statement(
                  TOKEN_NOISE,
                  TOKEN_LPAREN,
                  Print Expression(
                    Expression(
                      Term(
                        Power(
                          Factor(
                            Identifier(
                              TOKEN_ID: "x"
                            )
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_RPAREN,
                  TOKEN_SEMI
                )
              ),
              Statement(
                Assignment(
                  Identifier(
                    TOKEN_ID: "x"
                  ),
                  TOKEN_OPERATOR: "-=",
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "1"
                          )
                        )
                      )
                    )
                  )
                ),
                TOKEN_SEMI
              )
            ),
            TOKEN_RBRACE
          )
        )
      )
    ),
    Statement(
      Iterative Statement(
        TOKEN_DO,
        Do While Statement(
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Assignment(
                  Identifier(
                    TOKEN_ID: "myNumber"
                  ),
                  TOKEN_OPERATOR: "/=",
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "2"
                          )
                        )
                      )
                    )
                  )
                ),
                TOKEN_SEMI
              )
            ),
            TOKEN_RBRACE
          ),
          TOKEN_WHILE,
          TOKEN_LPAREN,
          Bool Expression(
            Bool Term(
              Bool Factor(
                Relational Expression(
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "myNumber"
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_OPERATOR: ">",
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Constant(
                            TOKEN_NUMBER: "0"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          TOKEN_RPAREN,
          TOKEN_SEMI
        )
      )
    ),
    Statement(
      Declaration statement(
        Declaration assignment statement(
          Data Type(
            TOKEN_DATATYPE: "int"
          ),
          Identifier List(
            Identifier(
              TOKEN_ID: "score"
            )
          ),
          TOKEN_OPERATOR: "=",
          Expression(
            Term(
              Power(
                Factor(
                  Constant(
                    TOKEN_NUMBER: "10"
                  )
                )
              )
            )
          ),
          TOKEN_SEMI
        )
      )
    ),
    Statement(
      Declaration statement(
        Declaration assignment statement(
          Data Type(
            TOKEN_DATATYPE: "int"
          ),
          Identifier List(
            Identifier(
              TOKEN_ID: "result"
            )
          ),
          TOKEN_OPERATOR: "=",
          Expression(
            Term(
              Power(
                Factor(
                  Constant(
                    TOKEN_NUMBER: "5"
                  )
                )
              )
            ),
            TOKEN_OPERATOR: "+",
            Term(
              Power(
                Factor(
                  Identifier(
                    TOKEN_ID: "a"
                  )
                )
              )
            )
          ),
          TOKEN_SEMI
        )
      )
    ),
    Statement(
      Declaration statement(
        Function Statement(
          TOKEN_DATATYPE: "int",
          TOKEN_FUNCTION,
          Identifier(
            TOKEN_ID: "add"
          ),
          TOKEN_LPAREN,
          Parameter List(
            Data Type(
              TOKEN_DATATYPE: "int"
            ),
            Identifier(
              TOKEN_ID: "a"
            ),
            TOKEN_COMMA,
            TOKEN_DATATYPE: "int",
            Identifier(
              TOKEN_ID: "b"
            )
          ),
          TOKEN_RPAREN,
          Body(
            TOKEN_LBRACE,
            Statements(
              Statement(
                Return Statement(
                  TOKEN_RETURN,
                  Expression(
                    Term(
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "a"
                          )
                        )
                      )
                    ),
                    TOKEN_OPERATOR: "+",
                    Term(
                      Power(
                        Factor(
                          Identifier(
                            TOKEN_ID: "b"
                          )
                        )
                      )
                    )
                  ),
                  TOKEN_SEMI
                )
              )
            ),
            TOKEN_RBRACE
          )
        )
      )
    ),
    Statement(
      Declaration statement(
        Array statement(
          Data Type(
            TOKEN_DATATYPE: "int"
          ),
          Identifier(
            TOKEN_ID: "number"
          ),
          TOKEN_LBRACKET,
          Constant(
            TOKEN_NUMBER: "5"
          ),
          TOKEN_RBRACKET,
          TOKEN_SEMI
        )
      )
    ),
    Statement(
      Conditional(
        TOKEN_IF,
        TOKEN_LPAREN,
        Bool Expression(
          Bool Term(
            Bool Factor(
              Relational Expression(
                Expression(
                  Term(
                    Power(
                      Factor(
                        Identifier(
                          TOKEN_ID: "height"
                        )
                      )
                    )
                  )
                ),
                TOKEN_OPERATOR: "==",
                Expression(
                  Term(
                    Power(
                      Factor(
                        Constant(
                          TOKEN_NUMBER: "2.1"
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        ),
        TOKEN_RPAREN,
        Body(
          TOKEN_LBRACE,
          Statements(
            Statement(
              Output Statement(
                TOKEN_NOISE,
                TOKEN_LPAREN,
                Print Expression(
                  Constant(
                    TOKEN_STRING: tall
                  )
                ),
                TOKEN_RPAREN,
                TOKEN_SEMI
              )
            )
          ),
          TOKEN_RBRACE
        )
      )
    )
  )
)